name: Deploy Documentation

on:
  push:
    branches:
      - migrate-to-mkdocs

permissions:
  contents: write

jobs:
  deploy_mkdocs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    # - name: Build and Deploy MkDocs
    #   run: |
    #     poetry run mkdocs gh-deploy --force
